### ISSUE TITLE
Tut: write a test that confirm that the language select is working

### ISSUE THREAD

**Issue by acidjunk** [acidjunk/recruitme_monolith#16]
Write a test to confirm that the language selector works as expected.

**Comment by hussamhadi** [comment]
fixed in #22

**Comment by acidjunk** [comment]
The change had a "side-effect" resulting into:
Did you rename developer.bio_en_us to developer.bio_en (a TextField)? [y/N] y
Did you rename developer.bio_nl_nl to developer.bio_nl (a TextField)? [y/N] y

Which I like :)
After running makemigrations & migrate all tests passed. Thanks!
